### ISSUE TITLE
U+2019 : RIGHT SINGLE QUOTATION MARK {single comma quotation mark} Used On Line 3081

### ISSUE THREAD

**Issue by DGDC** [PowershellScripts/SPOMod#3]
At C:\Program Files\WindowsPowerShell\Modules\SPOMod\SPOMod.psm1:3081 char:37
         [Parameter(ParameterSetName=â€™groupIdâ€™, Mandatory=$false)]

`’groupId’` should be `"groupId"`

**Comment by PowershellScripts** [comment]
Thanks!    Fixed.
