### ISSUE TITLE
ListTitle with spaces causes hangs

### ISSUE THREAD

**Issue by AHVFletch** [PowershellScripts/SPOMod#6]
Passing Get-SPOListItems a ListTitle string which contains a space causes a perpetual hang; Unable to resolve when containing string with quotations (I observe a 'list does not exist at URL' error). Passing nonexistent ListTitles with spaces also results in the same error.

**Comment by PowershellScripts** [comment]
Thanks for reporting. If you'd care to create a pull request, I'd love to merge it
